house_price_analytics:

  target: house_dev
  outputs:
    house_dev:
      type: clickhouse
      schema: house_dev
      host: 35.189.109.115
      password: ''
    
    house_test:
      type: clickhouse
      schema: house_test
      host: 35.189.109.115
      password: ''

    house_production:
      type: clickhouse
      schema: house_production
      host: 35.189.109.115
      password: ''
