house_price_analytics:

  target: hp_dev
  outputs:
    hp_dev:
      type: clickhouse
      schema: hp_dev
      host: 35.189.109.115
      password: ''
    
    hp_test:
      type: clickhouse
      schema: hp_test
      host: 35.189.109.115
      password: ''

    hp_production:
      type: clickhouse
      schema: hp_production
      host: 35.189.109.115
      password: ''
